// Auto-generated by: supabase gen types typescript --project-id <id>
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
// Placeholder until Supabase project is connected

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          first_name: string | null
          last_name: string | null
          farm_name: string
          farm_no: string | null
          farm_lat: number | null
          farm_lng: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          first_name?: string | null
          last_name?: string | null
          farm_name: string
          farm_no?: string | null
          farm_lat?: number | null
          farm_lng?: number | null
        }
        Update: {
          first_name?: string | null
          last_name?: string | null
          farm_name?: string
          farm_no?: string | null
          farm_lat?: number | null
          farm_lng?: number | null
          updated_at?: string
        }
      }
      employees: {
        Row: {
          id: string
          user_id: string
          name: string
          surname: string
          middle_name: string | null
          phone_number: string | null
          recommendation: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          surname: string
          middle_name?: string | null
          phone_number?: string | null
          recommendation?: string | null
          is_active?: boolean
        }
        Update: {
          name?: string
          surname?: string
          middle_name?: string | null
          phone_number?: string | null
          recommendation?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      buyers: {
        Row: {
          id: string
          user_id: string
          name: string
          pib: string | null
          jmbg: string | null
          phone: string | null
          address: string | null
          city: string | null
          email: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          pib?: string | null
          jmbg?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          email?: string | null
          is_active?: boolean
        }
        Update: {
          name?: string
          pib?: string | null
          jmbg?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          email?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      cultures: {
        Row: {
          id: string
          user_id: string
          culture_name: string
          is_active: boolean
          created_at: string
        }
        Insert: { id?: string; user_id: string; culture_name: string; is_active?: boolean }
        Update: { culture_name?: string; is_active?: boolean }
      }
      culture_types: {
        Row: {
          id: string
          user_id: string
          culture_id: string
          culture_type_name: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          culture_id: string
          culture_type_name: string
          is_active?: boolean
        }
        Update: { culture_type_name?: string; culture_id?: string; is_active?: boolean }
      }
      packaging: {
        Row: {
          id: string
          user_id: string
          packaging_type: string
          tara: number
          is_active: boolean
          created_at: string
        }
        Insert: { id?: string; user_id: string; packaging_type: string; tara?: number; is_active?: boolean }
        Update: { packaging_type?: string; tara?: number; is_active?: boolean }
      }
      plot_lists: {
        Row: { id: string; user_id: string; plot_list_name: string; created_at: string }
        Insert: { id?: string; user_id: string; plot_list_name: string }
        Update: { plot_list_name?: string }
      }
      plots: {
        Row: {
          id: string
          user_id: string
          plot_list_id: string | null
          plot_name: string
          plot_label: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plot_list_id?: string | null
          plot_name: string
          plot_label?: string | null
          is_active?: boolean
        }
        Update: {
          plot_list_id?: string | null
          plot_name?: string
          plot_label?: string | null
          is_active?: boolean
        }
      }
      barcodes: {
        Row: {
          id: string
          user_id: string
          employee_id: string | null
          culture_id: string | null
          culture_type_id: string | null
          packaging_id: string | null
          plot_id: string | null
          barcode_value: string
          tara: number | null
          neto: number | null
          bruto: number | null
          print_count: number
          is_storno: boolean
          storno_at: string | null
          storno_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          employee_id?: string | null
          culture_id?: string | null
          culture_type_id?: string | null
          packaging_id?: string | null
          plot_id?: string | null
          barcode_value: string
          tara?: number | null
          neto?: number | null
          bruto?: number | null
          print_count?: number
        }
        Update: {
          print_count?: number
          is_storno?: boolean
          storno_at?: string | null
          storno_reason?: string | null
        }
      }
      work_evaluations: {
        Row: {
          id: string
          user_id: string
          employee_id: string
          eval_date: string
          neto: number | null
          no_of_boxes: number | null
          evaluation: number | null
          pay_per_day: number | null
          expense_kg: number | null
          total: number | null
          fuel: number | null
          bonus: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          employee_id: string
          eval_date: string
          neto?: number | null
          no_of_boxes?: number | null
          evaluation?: number | null
          pay_per_day?: number | null
          expense_kg?: number | null
          total?: number | null
          fuel?: number | null
          bonus?: number | null
          notes?: string | null
        }
        Update: {
          employee_id?: string
          eval_date?: string
          neto?: number | null
          no_of_boxes?: number | null
          evaluation?: number | null
          pay_per_day?: number | null
          expense_kg?: number | null
          total?: number | null
          fuel?: number | null
          bonus?: number | null
          notes?: string | null
          updated_at?: string
        }
      }
      repurchase: {
        Row: {
          id: string
          user_id: string
          buyer_id: string
          culture_id: string
          repurchase_date: string
          neto: number
          no_of_boxes: number | null
          price_rsd: number | null
          price_eur: number | null
          income_rsd: number | null
          income_eur: number | null
          eur_rate: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          buyer_id: string
          culture_id: string
          repurchase_date: string
          neto: number
          no_of_boxes?: number | null
          price_rsd?: number | null
          price_eur?: number | null
          income_rsd?: number | null
          income_eur?: number | null
          eur_rate?: number | null
          notes?: string | null
        }
        Update: {
          buyer_id?: string
          culture_id?: string
          repurchase_date?: string
          neto?: number
          no_of_boxes?: number | null
          price_rsd?: number | null
          price_eur?: number | null
          income_rsd?: number | null
          income_eur?: number | null
          eur_rate?: number | null
          notes?: string | null
          updated_at?: string
        }
      }
      scheduler_events: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          start_at: string
          end_at: string | null
          color: string
          employee_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          start_at: string
          end_at?: string | null
          color?: string
          employee_id?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          start_at?: string
          end_at?: string | null
          color?: string
          employee_id?: string | null
          updated_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          stripe_price_id: string | null
          tier: 'free' | 'pro' | 'business'
          status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | 'paused'
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          trial_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          tier?: 'free' | 'pro' | 'business'
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | 'paused'
        }
        Update: {
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          tier?: 'free' | 'pro' | 'business'
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | 'paused'
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          trial_end?: string | null
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      subscription_tier: 'free' | 'pro' | 'business'
      subscription_status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | 'paused'
    }
  }
}
